# Generated by Django 5.1 on 2024-09-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('only_oneowner', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='fallback.png', upload_to='')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
