# Generated by Django 5.1 on 2024-11-05 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='slug',
        ),
        migrations.AddField(
            model_name='cars',
            name='body_style',
            field=models.CharField(default='SUV', max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='descripcion',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='en_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(default='Gasolina', max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='nuevo_usado',
            field=models.CharField(default='usado', max_length=100),
        ),
        migrations.AddField(
            model_name='cars',
            name='precio',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='cars',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cars',
            name='marca',
            field=models.CharField(default='ACURA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cars',
            name='modelo',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
